[[main]]
  identifier = "about"
  name = "关于"
  url = "about"
  weight = 1

[[main]]
  identifier = "archive"
  name = "归档"
  url = "archive"
  weight = 2

[[main]]
  identifier = "gallery"
  name = "分类"
  url = "gallery"
  weight = 3

[[main]]
  identifier = "posts"
  name = "最新发布"
  url = "posts"
  weight = 4

[[main]]
  identifier = "age-plus"
  name = "岁月如屑"
  url = "age-plus"
  weight = 4