baseURL: https://blog-millerfour.netlify.app
title: 人生大事儿
theme: hugo-coder
languageCode: zh-cn
defaultContentLanguage: zh-cn
paginate: 20
pygmentsStyle: bw
pygmentsCodeFences: true
pygmentsCodeFencesGuessSyntax: true
enableEmoji: true
params:
  author: MillerFour 
  description: MillerFour's Coffee Life
  keywords: blog,developer,personal
  info:
    - Full Stack DevOps
    - Magician
  avatarURL: images/avatar.jpg
  dateFormat: January 2, 2006
  since: 2022
  commit: https://github.com/luizdepra/hugo-coder/tree/
  rtl: false
  colorScheme: auto
  hideColorSchemeToggle: false
  maxSeeAlsoItems: 5
  customCSS: []
  customSCSS: []
  customJS: []
  csp:
    childsrc:
      - "'self'"
    fontsrc:
      - "'self'"
      - https://fonts.gstatic.com
      - https://cdn.jsdelivr.net/
    formaction:
      - "'self'"
    framesrc:
      - "'self'"
    imgsrc:
      - "'self'"
    objectsrc:
      - "'none'"
    stylesrc:
      - "'self'"
      - "'unsafe-inline'"
      - https://fonts.googleapis.com/
      - https://cdn.jsdelivr.net/
    scriptsrc:
      - "'self'"
      - "'unsafe-inline'"
      - https://www.google-analytics.com
      - https://cdn.jsdelivr.net/
    prefetchsrc:
      - "'self'"
    connectsrc:
      - "'self'"
      - https://www.google-analytics.com
  social:
    - name: Github
      icon: fa fa-2x fa-github
      weight: 1
      url: https://github.com/MillerFour/
    - name: bilibili
      icon: fa fa-2x fa-linkedin
      weight: 4
      url: https://www.bilibili.com/
    - name: Medium
      icon: fa fa-2x fa-medium
      weight: 5
      url: https://medium.com/@johndoe
taxonomies:
  category: categories
  series: series
  tag: tags
  author: authors
languages:
  zh-cn:
    languageName: ":简体中文:"
    menu:
      main:
        - name: 关于
          weight: 1
          url: about/
        - name: 博客
          weight: 2
          url: posts/
        - name: 项目
          weight: 3
          url: projects/
        - name: 找到我
          weight: 5
          url: contact/
  # en:
  #   languageName: ":uk:"
  #   menu:
  #     main:
  #       - name: About
  #         weight: 1
  #         url: about/
  #       - name: Blog
  #         weight: 2
  #         url: posts/
  #       - name: Projects
  #         weight: 3
  #         url: projects/
  #       - name: Contact me
  #         weight: 5
  #         url: contact/
